In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
deliveryPath = "IPL2025/deliveries.csv";
matchesPath = "IPL2025/matches.csv";
orange_capPath = "IPL2025/orange_cap.csv";
purple_capPath = "IPL2025/purple_cap.csv";

In [6]:
delivery_dataset = pd.read_csv(deliveryPath);
matches_dataset = pd.read_csv(matchesPath);
orange_cap_dataset = pd.read_csv(orange_capPath);
purple_cap_dataset = pd.read_csv(purple_capPath);

In [8]:
delivery_dataset.head()

,match_no,date,stage,venue,batting_team,bowling_team,innings,over,striker,bowler,runs_of_bat,extras,wide,legbyes,byes,noballs,wicket_type,player_dismissed,fielder
0,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.1,de Kock,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN
1,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.2,de Kock,Hazlewood,4,0,0,0,0,0,NaN,NaN,NaN
2,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.3,de Kock,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN
3,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.4,de Kock,Hazlewood,0,0,0,0,0,0,NaN,NaN,NaN
4,1,"Mar 22, 2025",League stage,"Eden Gardens, Kolkata",KKR,RCB,1,0.5,de Kock,Hazlewood,0,0,0,0,0,0,caught,de Kock,Jitesh Sharma

In [10]:
delivery_dataset.shape

(17183, 19)

In [12]:
delivery_dataset.columns

Index(['match_no', 'date', 'stage', 'venue', 'batting_team', 'bowling_team',
       'innings', 'over', 'striker', 'bowler', 'runs_of_bat', 'extras', 'wide',
       'legbyes', 'byes', 'noballs', 'wicket_type', 'player_dismissed',
       'fielder'],
      dtype='object')

In [14]:
delivery_dataset.isna().sum()

match_no                0
date                    0
stage                   0
venue                   0
batting_team            0
bowling_team            0
innings                 0
over                    0
striker                 0
bowler                  0
runs_of_bat             0
extras                  0
wide                    0
legbyes                 0
byes                    0
noballs                 0
wicket_type         16311
player_dismissed    16311
fielder             16504
dtype: int64

In [16]:
# Top 10 bowlers who had the most number of dot balls
dotballs = delivery_dataset[(delivery_dataset["runs_of_bat"] == 0)
& (delivery_dataset["extras"] == 0)
& (delivery_dataset["wide"] == 0)
& (delivery_dataset["legbyes"] == 0)
& (delivery_dataset["byes"] == 0)
& (delivery_dataset["noballs"] == 0)];
most_dot_balls = dotballs.groupby("bowler").size().reset_index(name="Number of dot balls").sort_values(by="Number of dot balls" ,ascending=False).head(10).reset_index(drop=True);
most_dot_balls

                bowler  Number of dot balls
0                Siraj                  141
1              Prasidh                  135
2       Arshdeep Singh                  134
3        Khaleel Ahmed                  131
4               Bumrah                  125
5                Boult                  124
6            Hazlewood                  117
7          Bhuvneshwar                  116
8  Varun Chakaravarthy                  114
9              Cummins                  111

In [18]:
# Most wide and no balls
noballs = delivery_dataset[(delivery_dataset["wide"] != 0) | (delivery_dataset["noballs"] != 0)]
# noballs.shape
most_extras = noballs.groupby("bowler").size().reset_index(name="Number of extras").sort_values(by="Number of extras", ascending=False).head(10).reset_index(drop=True);
most_extras

             bowler  Number of extras
0         Pathirana                33
1             Siraj                22
2     Harshal Patel                21
3  Tushar Deshpande                19
4        Theekshana                18
5      Jofra Archer                18
6    Sandeep Sharma                18
7            Chahar                17
8      Mukesh Kumar                17
9    Arshdeep Singh                17

In [20]:
# Most bowling friendly pitch/venue
wicket_deliveries = delivery_dataset[delivery_dataset["wicket_type"].notna()]
wicket_deliveries.shape

(872, 19)

In [22]:
venuesByWickets = wicket_deliveries.groupby("venue").size().reset_index(name="Wickets fallen").sort_values(by="Wickets fallen", ascending=False).reset_index(drop=True);
venueByMatchesPlayed = delivery_dataset.groupby("venue")["match_no"].nunique().reset_index(name="Number of matches played").sort_values(by="Number of matches played", ascending=False).reset_index(drop=True);
df = pd.merge(venueByMatchesPlayed, venuesByWickets, on="venue");
df

,venue,Number of matches played,Wickets fallen
0,"Narendra Modi Stadium, Ahmedabad",9,116
1,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,8,87
2,"Arun Jaitley Stadium, Delhi",7,85
3,"Eden Gardens, Kolkata",7,78
4,"Sawai Mansingh Stadium, Jaipur",7,67
5,"Wankhede Stadium, Mumbai",7,90
6,"MA Chidambaram Stadium, Chennai",6,83
7,"Rajiv Gandhi International Stadium, Hyderabad",6,63
8,"M.Chinnaswamy Stadium, Bengaluru",5,59
9,Maharaja Yadavindra Singh International Cricke...,5,65
10,"Barsapara Cricket Stadium, Guwahati",2,26
11,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,2,30
12,"Himachal Pradesh Cricket Association Stadium, ...",1,12
13,Maharaja Yadavindra Singh International Cricke...,1,11

In [24]:
matches_dataset.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_result,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 22,2025","Eden Gardens, Kolkata",KKR,RCB,League,RCB,Bowl,174.0,8.0,...,completed,RCB,NaN,7,22.0,Krunal Pandya,Virat Kohli,59.0,Krunal Pandya,3--29
1,2,"March 23,2025","Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,League,RR,Bowl,286.0,6.0,...,completed,SRH,44,NaN,0.0,Ishan Kishan,Ishan Kishan,106.0,Tushar Deshpande,3--44
2,3,"March 23,2025","MA Chidambaram Stadium, Chennai",CSK,MI,League,CSK,Bowl,155.0,9.0,...,completed,CSK,NaN,4,5.0,Noor Ahmad,Rachin Ravindra,65.0,Noor Ahmad,4--18
3,4,"March 24,2025","ACA-VDCA Cricket Stadium, Vishakhapatnam",DC,LSG,League,DC,Bowl,209.0,8.0,...,completed,DC,NaN,1,3.0,Ashutosh Sharma,Nicholas Pooran,75.0,Mitchell Starc,3--42
4,5,"March 25,2025","Narendra Modi Stadium, Ahmedabad",GT,PBKS,League,GT,Bowl,243.0,5.0,...,completed,PBKS,11,NaN,0.0,Shreyas Iyer,Shreyas Iyer,97.0,Sai Kishore,3--30

In [50]:
matches_dataset.shape

(74, 24)

In [52]:
def get_batting_first(row):
    if row['toss_decision'] == 'Bat':
        return row['toss_winner']
    else:  # Toss winner chose to bowl
        return row['team2'] if row['toss_winner'] == row['team1'] else row['team1'];

def get_bowling_first(row):
    if row['batting_first_team'] == row['team1']:
        return row['team2'];
    else:
        return row['team1'];

matches_dataset['batting_first_team'] = matches_dataset.apply(get_batting_first, axis=1)
matches_dataset['bowling_first_team'] = matches_dataset.apply(get_bowling_first, axis=1)

In [58]:
wonBatting = matches_dataset[matches_dataset['batting_first_team'] == matches_dataset['match_winner']];
# wonBatting.shape
wonBatting.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,batting_first_team,bowling_first_team
1,2,"March 23,2025","Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,League,RR,Bowl,286.0,6.0,...,44,NaN,0.0,Ishan Kishan,Ishan Kishan,106.0,Tushar Deshpande,3--44,SRH,RR
4,5,"March 25,2025","Narendra Modi Stadium, Ahmedabad",GT,PBKS,League,GT,Bowl,243.0,5.0,...,11,NaN,0.0,Shreyas Iyer,Shreyas Iyer,97.0,Sai Kishore,3--30,PBKS,GT
7,8,"March 28,2025","MA Chidambaram Stadium, Chennai",CSK,RCB,League,CSK,Bowl,196.0,7.0,...,50,NaN,0.0,Rajat Patidar,Rajat Patidar,51.0,Josh Hazlewood,3--21,RCB,CSK
8,9,"March 29,2025","Narendra Modi Stadium, Ahmedabad",GT,MI,League,MI,Bowl,196.0,8.0,...,36,NaN,0.0,Prasidh Krishna,Sai Sudarshan,63.0,Prasidh Krishna,2--18,GT,MI
10,11,"March 30,2025","Barsapara Stadium, Guwahati",RR,CSK,League,CSK,Bowl,182.0,9.0,...,6,NaN,0.0,Nitish Rana,Nitish Rana,81.0,Wanindu Hasranga,4--35,RR,CSK

In [60]:
wonBowling = matches_dataset[matches_dataset['bowling_first_team'] == matches_dataset['match_winner']];
# wonBowling.shape
wonBowling.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,batting_first_team,bowling_first_team
0,1,"March 22,2025","Eden Gardens, Kolkata",KKR,RCB,League,RCB,Bowl,174.0,8.0,...,NaN,7,22.0,Krunal Pandya,Virat Kohli,59.0,Krunal Pandya,3--29,KKR,RCB
2,3,"March 23,2025","MA Chidambaram Stadium, Chennai",CSK,MI,League,CSK,Bowl,155.0,9.0,...,NaN,4,5.0,Noor Ahmad,Rachin Ravindra,65.0,Noor Ahmad,4--18,MI,CSK
3,4,"March 24,2025","ACA-VDCA Cricket Stadium, Vishakhapatnam",DC,LSG,League,DC,Bowl,209.0,8.0,...,NaN,1,3.0,Ashutosh Sharma,Nicholas Pooran,75.0,Mitchell Starc,3--42,LSG,DC
5,6,"March 26,2025","Barsapara Stadium, Guwahati",RR,KKR,League,KKR,Bowl,151.0,9.0,...,NaN,8,15.0,Quinton de Kock,Quinton de Kock,97.0,Varun Chakravarthy,2--17,RR,KKR
6,7,"March 27,2025","Rajiv Gandhi International Stadium, Hyderabad",SRH,LSG,League,LSG,Bowl,190.0,9.0,...,NaN,5,23.0,Shardul Thakur,Nicholas Pooran,70.0,Shardul Thakur,4--34,SRH,LSG

In [74]:
features = matches_dataset[['venue', 'team1', 'team2', 'toss_winner', 'toss_decision']];
features

,venue,team1,team2,toss_winner,toss_decision
0,"Eden Gardens, Kolkata",KKR,RCB,RCB,Bowl
1,"Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,RR,Bowl
2,"MA Chidambaram Stadium, Chennai",CSK,MI,CSK,Bowl
3,"ACA-VDCA Cricket Stadium, Vishakhapatnam",DC,LSG,DC,Bowl
4,"Narendra Modi Stadium, Ahmedabad",GT,PBKS,GT,Bowl
...,...,...,...,...,...
69,"Ekana Cricket Stadium, Lucknow",LSG,RCB,RCB,Bowl
70,"New PCA Cricket Stadium, Mullanpur",PBKS,RCB,RCB,Bowl
71,"New PCA Cricket Stadium, Mullanpur",GT,MI,MI,Bat
72,"Narendra Modi Stadium, Ahmedabad",PBKS,MI,PBKS,Bowl
73,"Narendra Modi Stadium, Ahmedabad",RCB,PBKS,PBKS,Bowl

In [76]:
encoded_features = pd.get_dummies(features, columns=['venue', 'team1', 'team2', 'toss_winner', 'toss_decision'], drop_first=True);
encoded_features

,"venue_Arun Jaitley Stadium, Delhi","venue_Barsapara Stadium, Guwahati","venue_Eden Gardens, Kolkata","venue_Ekana Cricket Stadium, Lucknow","venue_HPCA Stadium, Dharamshala","venue_M. Chinnaswamy Stadium, Bangalore","venue_MA Chidambaram Stadium, Chennai","venue_Narendra Modi Stadium, Ahmedabad","venue_New PCA Cricket Stadium, Mullanpur","venue_Rajiv Gandhi International Stadium, Hyderabad",...,toss_winner_DC,toss_winner_GT,toss_winner_KKR,toss_winner_LSG,toss_winner_MI,toss_winner_PBKS,toss_winner_RCB,toss_winner_RR,toss_winner_SRH,toss_decision_Bowl
0,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
1,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,True
2,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
70,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
71,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
72,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,True
73,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,True

In [78]:
from sklearn.model_selection import train_test_split;

X = encoded_features;
y = matches_dataset['batting_first_team'];

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [80]:
from sklearn.linear_model import LogisticRegression
modelLogistic = LogisticRegression(max_iter=1000)
modelLogistic.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [84]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix;

y_pred = modelLogistic.predict(X_test)
confusion_m = confusion_matrix(y_test, y_pred);
print('Accuracy:', accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
# print('Confusion matrix: ', confusion_m)

Accuracy: 0.4
              precision    recall  f1-score   support

         CSK       0.00      0.00      0.00         0
          DC       0.00      0.00      0.00         3
          GT       0.00      0.00      0.00         0
         KKR       0.50      1.00      0.67         1
         LSG       0.50      0.50      0.50         2
          MI       0.67      1.00      0.80         2
        PBKS       0.00      0.00      0.00         2
         RCB       0.50      1.00      0.67         1
          RR       0.00      0.00      0.00         2
         SRH       1.00      0.50      0.67         2

    accuracy                           0.40        15
   macro avg       0.32      0.40      0.33        15
weighted avg       0.36      0.40      0.35        15

/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [95]:
matches_dataset['batting_first_win'] = (matches_dataset['match_winner'] == matches_dataset['batting_first_team']).astype(int)
matches_dataset.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,batting_first_team,bowling_first_team,batting_first_win
0,1,"March 22,2025","Eden Gardens, Kolkata",KKR,RCB,League,RCB,Bowl,174.0,8.0,...,7,22.0,Krunal Pandya,Virat Kohli,59.0,Krunal Pandya,3--29,KKR,RCB,0
1,2,"March 23,2025","Rajiv Gandhi International Stadium, Hyderabad",SRH,RR,League,RR,Bowl,286.0,6.0,...,NaN,0.0,Ishan Kishan,Ishan Kishan,106.0,Tushar Deshpande,3--44,SRH,RR,1
2,3,"March 23,2025","MA Chidambaram Stadium, Chennai",CSK,MI,League,CSK,Bowl,155.0,9.0,...,4,5.0,Noor Ahmad,Rachin Ravindra,65.0,Noor Ahmad,4--18,MI,CSK,0
3,4,"March 24,2025","ACA-VDCA Cricket Stadium, Vishakhapatnam",DC,LSG,League,DC,Bowl,209.0,8.0,...,1,3.0,Ashutosh Sharma,Nicholas Pooran,75.0,Mitchell Starc,3--42,LSG,DC,0
4,5,"March 25,2025","Narendra Modi Stadium, Ahmedabad",GT,PBKS,League,GT,Bowl,243.0,5.0,...,NaN,0.0,Shreyas Iyer,Shreyas Iyer,97.0,Sai Kishore,3--30,PBKS,GT,1

In [97]:
y = matches_dataset['batting_first_win'];
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [99]:
modelLogistic = LogisticRegression(max_iter=1000)
modelLogistic.fit(X_train, y_train)
y_pred = modelLogistic.predict(X_test)

In [101]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=['Bowling First Wins', 'Batting First Wins']))

Accuracy: 0.5333333333333333
Confusion Matrix:
 [[6 4]
 [3 2]]
                    precision    recall  f1-score   support

Bowling First Wins       0.67      0.60      0.63        10
Batting First Wins       0.33      0.40      0.36         5

          accuracy                           0.53        15
         macro avg       0.50      0.50      0.50        15
      weighted avg       0.56      0.53      0.54        15

In [105]:
next_match = pd.DataFrame({
    'venue': ['Wankhede Stadium, Mumbai'],
    'team1': ['MI'],
    'team2': ['CSK'],
    'toss_winner': ['MI'],
    'toss_decision': ['Bat']
})

# Apply same encoding as training data
next_match_encoded = pd.get_dummies(next_match)
# Align columns with training data
next_match_encoded = next_match_encoded.reindex(columns=X.columns, fill_value=0)

# Predict
prediction = modelLogistic.predict(next_match_encoded)
print("Batting first wins?" , "Yes" if prediction[0] == 1 else "No")

Batting first wins? Yes